pipeline {
    agent any
    environment {
          dockerhub=credentials('dockerid')
          NAME = "pythonapptest"
          VERSION = "1.2.9"
          IMAGE = "${NAME}:${VERSION}"

           }
    stages {
        stage('Scanning Repository') {
            steps {
                echo 'Repository Scanned , Done !!'
                echo "${IMAGE}"
            }
        }
        stage('Build Image') {
        steps {
            sh "pwd"
            sh 'docker build -f ./docker/Dockerfile -t ${IMAGE}  ./docker/'
            }
       }
        stage('Pushing To DockerHub') {
        steps {
            sh 'docker tag  ${IMAGE} chetanbisht11/${IMAGE}'
            sh 'echo $dockerhub_PSW | docker login -u  $dockerhub_USR --password-stdin'
            sh 'docker push chetanbisht11/${IMAGE}'

            }
       }
    }
}
