pipeline {
    agent any
    environment {
          dockerhub=credentials('dockerid')

           }
    stages {
        stage('Scanning Repository') {
            steps {
                echo 'Repository Scanned , Done!!'
            }
        }
        stage('Build Image') {
        steps {
            sh "pwd"
            sh 'docker build -f ./docker/Dockerfile -t pythonapptest:1.2.5  ./docker/'
            }
       }
        stage('Pushing To DockerHub') {
        steps {
            sh 'docker tag  pythonapptest:1.2.5 chetanbisht11/pythonapptest:1.2.5'
            sh 'echo $dockerhub_PSW | docker login -u  $dockerhub_USR --password-stdin'
            sh 'docker push chetanbisht11/pythonapptest:1.2.5'

            }
       }
    }
}
