---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    fluxcd.io/automated: "true"
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: example-apps
        image:  docker.io/chetanbisht11/pythonapptest:1.0.1   # {"$imagepolicy": "flux-system:pythonapptest"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
