---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.example-apps: semver:~1
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: example-apps
        image:  docker.io/chetanbisht11/pythonapptest:1.0.4   
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
