apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: example-apps
        image: docker.io/chetanbisht11/pythonapptest:1.2.13 # {"$imagepolicy": "flux-system:imageupdate"}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
